app:
  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 30s
  stackoverflowBaseUrl: https://api.stackexchange.com/2.3
  githubBaseUrl: https://api.github.com
  botBaseUrl: ${BOT_BASE_URL}
  githubAccessToken: ${GIT_HUB_ACCESS_TOKEN}
  databaseAccessType: jpa
  use-queue: false
  kafka-prop:
    acks: all
    batch-size: 512
    max-request-size: 512
    linger-ms: 5000
    bootstrap-server: 127.0.0.1:9092
    topic-prop:
      name: main
      partitions: 1
      replicas: 1
  retry-prop:
    attempt: 3
    delay: 10s
    linear-step: 10s
    retry-type: exponential
    status-code:
      - 400
      - 500


springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: scrapper
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/"
      exposure:
        include:
          - health
          - info
          - prometheus
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}
