scrape_configs:
  - job_name: scrapper
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: bot
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8091']
